In [11]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler

# Raw dataset
df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 2, 5],
    'age':         [25, np.nan, 35, np.nahn, np.nan, 40],
    'city':        ['Mumbai', 'Delhi', np.nan, 'Mumbai', 'Delhi', np.nan],
    'gender':      ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'annual_income': [40000, 80000, 60000, 120000, 80000, 95000]
})

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    6 non-null      int64
 1   age            3 non-null      float64
 2   city           4 non-null      object
 3   gender         6 non-null      object
 4   annual_income  6 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 372.0+ bytes

In [13]:
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2   NaN   Delhi  Female          80000
2            3  35.0     NaN  Female          60000
3            4   NaN  Mumbai    Male         120000
4            2   NaN   Delhi  Female          80000
5            5  40.0     NaN    Male          95000

In [14]:
df.isnull().sum()

customer_id      0
age              3
city             2
gender           0
annual_income    0
dtype: int64

In [15]:
#Task 1: Clean the Data
# Impute missing values
df['age'].fillna(df['age'].median(), inplace=True)
df['city'].fillna(df['city'].mode()[0], inplace=True)

# Remove duplicates
df = df.drop_duplicates()

print("Cleaned Data:\n", df)

Cleaned Data:
    customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0   Delhi  Female          60000
3            4  35.0  Mumbai    Male         120000
5            5  40.0   Delhi    Male          95000

/tmp/ipykernel_2713/2438936935.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(), inplace=True)
/tmp/ipykernel_2713/2438936935.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['city'].fillna(df['city'].mode()[0], inplace=True)

In [16]:
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0   Delhi  Female          60000
3            4  35.0  Mumbai    Male         120000
5            5  40.0   Delhi    Male          95000

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 5
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      int64
 1   age            5 non-null      float64
 2   city           5 non-null      object
 3   gender         5 non-null      object
 4   annual_income  5 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 240.0+ bytes

In [18]:
# Task 2: Encode Categorical Columns
# One-Hot Encoding for city
df = pd.get_dummies(df, columns=['city'], prefix='city')

# Label Encoding for gender
le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])

print("\nEncoded Data:\n", df)

Encoded Data:
    customer_id   age  gender  annual_income  city_Delhi  city_Mumbai
0            1  25.0       1          40000       False         True
1            2  35.0       0          80000        True        False
2            3  35.0       0          60000        True        False
3            4  35.0       1         120000       False         True
5            5  40.0       1          95000        True        False

In [19]:
df.columns

Index(['customer_id', 'age', 'gender', 'annual_income', 'city_Delhi',
       'city_Mumbai'],
      dtype='object')

In [20]:
#Task 3: Scale Numerical Features
# Select numerical columns
num_cols = ['age', 'annual_income']

# Min-Max Scaling
minmax_scaler = MinMaxScaler()
df_minmax = df.copy()
df_minmax[num_cols] = minmax_scaler.fit_transform(df[num_cols])
print("\nMin-Max Scaled Data:\n", df_minmax)

# Standardisation
std_scaler = StandardScaler()
df_std = df.copy()
df_std[num_cols] = std_scaler.fit_transform(df[num_cols])
print("\nStandardised Data:\n", df_std)

Min-Max Scaled Data:
    customer_id       age  gender  annual_income  city_Delhi  city_Mumbai
0            1  0.000000       1         0.0000       False         True
1            2  0.666667       0         0.5000        True        False
2            3  0.666667       0         0.2500        True        False
3            4  0.666667       1         1.0000       False         True
5            5  1.000000       1         0.6875        True        False

Standardised Data:
    customer_id       age  gender  annual_income  city_Delhi  city_Mumbai
0            1 -1.837117       1      -1.410970       False         True
1            2  0.204124       0       0.036179        True        False
2            3  0.204124       0      -0.687396        True        False
3            4  0.204124       1       1.483328       False         True
5            5  1.224745       1       0.578860        True        False